
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AVANZA BAJA_PLUMA GIRA_DERECHA GIRA_IZQUIERDA LBRACKET LEVANTA_PLUMA NUMERO RBRACKET REPITE SIinstrucciones : instruccion\n                         | instrucciones instruccioninstruccion : AVANZA NUMERO\n                       | GIRA_IZQUIERDA NUMERO\n                       | GIRA_DERECHA NUMERO\n                       | LEVANTA_PLUMA\n                       | BAJA_PLUMAinstruccion : REPITE NUMERO LBRACKET instrucciones RBRACKETinstruccion : SI NUMERO LBRACKET instrucciones RBRACKET'
    
_lr_action_items = {'AVANZA':([0,1,2,6,7,10,11,12,13,16,17,18,19,20,21,],[3,3,-1,-6,-7,-2,-3,-4,-5,3,3,3,3,-8,-9,]),'GIRA_IZQUIERDA':([0,1,2,6,7,10,11,12,13,16,17,18,19,20,21,],[4,4,-1,-6,-7,-2,-3,-4,-5,4,4,4,4,-8,-9,]),'GIRA_DERECHA':([0,1,2,6,7,10,11,12,13,16,17,18,19,20,21,],[5,5,-1,-6,-7,-2,-3,-4,-5,5,5,5,5,-8,-9,]),'LEVANTA_PLUMA':([0,1,2,6,7,10,11,12,13,16,17,18,19,20,21,],[6,6,-1,-6,-7,-2,-3,-4,-5,6,6,6,6,-8,-9,]),'BAJA_PLUMA':([0,1,2,6,7,10,11,12,13,16,17,18,19,20,21,],[7,7,-1,-6,-7,-2,-3,-4,-5,7,7,7,7,-8,-9,]),'REPITE':([0,1,2,6,7,10,11,12,13,16,17,18,19,20,21,],[8,8,-1,-6,-7,-2,-3,-4,-5,8,8,8,8,-8,-9,]),'SI':([0,1,2,6,7,10,11,12,13,16,17,18,19,20,21,],[9,9,-1,-6,-7,-2,-3,-4,-5,9,9,9,9,-8,-9,]),'$end':([1,2,6,7,10,11,12,13,20,21,],[0,-1,-6,-7,-2,-3,-4,-5,-8,-9,]),'RBRACKET':([2,6,7,10,11,12,13,18,19,20,21,],[-1,-6,-7,-2,-3,-4,-5,20,21,-8,-9,]),'NUMERO':([3,4,5,8,9,],[11,12,13,14,15,]),'LBRACKET':([14,15,],[16,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'instrucciones':([0,16,17,],[1,18,19,]),'instruccion':([0,1,16,17,18,19,],[2,10,2,2,10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> instrucciones","S'",1,None,None,None),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones','parser.py',10),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones','parser.py',11),
  ('instruccion -> AVANZA NUMERO','instruccion',2,'p_instruccion','parser.py',19),
  ('instruccion -> GIRA_IZQUIERDA NUMERO','instruccion',2,'p_instruccion','parser.py',20),
  ('instruccion -> GIRA_DERECHA NUMERO','instruccion',2,'p_instruccion','parser.py',21),
  ('instruccion -> LEVANTA_PLUMA','instruccion',1,'p_instruccion','parser.py',22),
  ('instruccion -> BAJA_PLUMA','instruccion',1,'p_instruccion','parser.py',23),
  ('instruccion -> REPITE NUMERO LBRACKET instrucciones RBRACKET','instruccion',5,'p_instruccion_repite','parser.py',40),
  ('instruccion -> SI NUMERO LBRACKET instrucciones RBRACKET','instruccion',5,'p_instruccion_condicional','parser.py',47),
]
