
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AVANZA GIRA_DERECHA GIRA_IZQUIERDA LBRACKET NUMERO RBRACKET REPITEinstrucciones : instruccion\n                     | instrucciones instruccioninstruccion : AVANZA NUMERO\n                   | GIRA_IZQUIERDA NUMERO\n                   | GIRA_DERECHA NUMEROinstruccion : REPITE NUMERO LBRACKET instrucciones RBRACKET'
    
_lr_action_items = {'AVANZA':([0,1,2,7,8,9,10,12,13,14,],[3,3,-1,-2,-3,-4,-5,3,3,-6,]),'GIRA_IZQUIERDA':([0,1,2,7,8,9,10,12,13,14,],[4,4,-1,-2,-3,-4,-5,4,4,-6,]),'GIRA_DERECHA':([0,1,2,7,8,9,10,12,13,14,],[5,5,-1,-2,-3,-4,-5,5,5,-6,]),'REPITE':([0,1,2,7,8,9,10,12,13,14,],[6,6,-1,-2,-3,-4,-5,6,6,-6,]),'$end':([1,2,7,8,9,10,14,],[0,-1,-2,-3,-4,-5,-6,]),'RBRACKET':([2,7,8,9,10,13,14,],[-1,-2,-3,-4,-5,14,-6,]),'NUMERO':([3,4,5,6,],[8,9,10,11,]),'LBRACKET':([11,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'instrucciones':([0,12,],[1,13,]),'instruccion':([0,1,12,13,],[2,7,2,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> instrucciones","S'",1,None,None,None),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones','lexysint.py',52),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones','lexysint.py',53),
  ('instruccion -> AVANZA NUMERO','instruccion',2,'p_instruccion','lexysint.py',61),
  ('instruccion -> GIRA_IZQUIERDA NUMERO','instruccion',2,'p_instruccion','lexysint.py',62),
  ('instruccion -> GIRA_DERECHA NUMERO','instruccion',2,'p_instruccion','lexysint.py',63),
  ('instruccion -> REPITE NUMERO LBRACKET instrucciones RBRACKET','instruccion',5,'p_instruccion_repite','lexysint.py',73),
]
